---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: ${CLUSTER_NAME}
  name: master-${REGION}
spec:
  additionalUserData:
  - name: myscript.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      cat <<EOT >> /etc/sysctl.d/999-testground.conf
      net.core.somaxconn = 131072
      net.netfilter.nf_conntrack_max = 1048576
      net.ipv4.tcp_max_syn_backlog = 131072
      net.core.netdev_max_backlog = 524288
      net.ipv4.ip_local_port_range = 10000 65535
      net.ipv4.tcp_tw_recycle = 1
      net.ipv4.tcp_tw_reuse = 1
      net.core.rmem_max = 4194304
      net.core.wmem_max = 4194304
      net.ipv4.tcp_mem = 262144 524288 1572864
      net.ipv4.tcp_rmem = 16384 131072 4194304
      net.ipv4.tcp_wmem = 16384 131072 4194304
      net.ipv4.neigh.default.gc_thresh2 = 4096
      net.ipv4.neigh.default.gc_thresh3 = 32768
      EOT
  image: ${IMAGE_NAME}
  machineType: ${MASTER_NODE_TYPE}
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-${REGION}
  role: Master
  subnets:
  - ${ZONE_A}
  zones:
  - ${ZONE_A}

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: ${CLUSTER_NAME}
  name: nodes
spec:
  additionalUserData:
  - name: myscript.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      cat <<EOT >> /etc/sysctl.d/999-testground.conf
      net.core.somaxconn = 131072
      net.netfilter.nf_conntrack_max = 1048576
      net.ipv4.tcp_max_syn_backlog = 131072
      net.core.netdev_max_backlog = 524288
      net.ipv4.ip_local_port_range = 10000 65535
      net.ipv4.tcp_tw_recycle = 1
      net.ipv4.tcp_tw_reuse = 1
      net.core.rmem_max = 4194304
      net.core.wmem_max = 4194304
      net.ipv4.tcp_mem = 262144 524288 1572864
      net.ipv4.tcp_rmem = 16384 131072 4194304
      net.ipv4.tcp_wmem = 16384 131072 4194304
      net.ipv4.neigh.default.gc_thresh2 = 4096
      net.ipv4.neigh.default.gc_thresh3 = 32768
      EOT
  cloudLabels:
    testground.node.role.plan: "true"
  image: ${IMAGE_NAME}
  machineType: ${WORKER_NODE_TYPE}
  maxSize: ${WORKER_NODES}
  minSize: ${WORKER_NODES}
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
    testground.node.role.plan: "true"
  role: Node
  subnets:
  - ${ZONE_A}
  - ${ZONE_B}
  zones:
  - ${ZONE_A}
  - ${ZONE_B}

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: ${CLUSTER_NAME}
  name: tginfra
spec:
  additionalUserData:
  - name: myscript.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      cat <<EOT >> /etc/sysctl.d/999-testground.conf
      net.core.somaxconn = 131072
      net.netfilter.nf_conntrack_max = 1048576
      net.ipv4.tcp_max_syn_backlog = 131072
      net.core.netdev_max_backlog = 524288
      net.ipv4.ip_local_port_range = 10000 65535
      net.ipv4.tcp_tw_recycle = 1
      net.ipv4.tcp_tw_reuse = 1
      net.core.rmem_max = 4194304
      net.core.wmem_max = 4194304
      net.ipv4.tcp_mem = 262144 524288 1572864
      net.ipv4.tcp_rmem = 16384 131072 4194304
      net.ipv4.tcp_wmem = 16384 131072 4194304
      net.ipv4.neigh.default.gc_thresh2 = 4096
      net.ipv4.neigh.default.gc_thresh3 = 32768
      EOT
  cloudLabels:
    testground.node.role.infra: "true"
  image: ${IMAGE_NAME}
  machineType: ${INFRA_NODE_TYPE}
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: tginfra
    testground.node.role.infra: "true"
  role: Node
  subnets:
  - ${ZONE_A}
  - ${ZONE_B}
  zones:
  - ${ZONE_A}
  - ${ZONE_B}

